### ISSUE TITLE
Is it possible to support attachments?

### ISSUE THREAD

**Issue by senj** [matt-github-acct/dotnetcore-slackbot#3]
Hey, great project it's really easy to get started.
Do you think it's possible to add attachment support?

Thanks

**Comment by mattcbaker** [comment]
I think that sounds awesome! Is your goal to send attachments from your slackbot? What kind of stuff would you want to send?

**Comment by senj** [comment]
Yes because then one could add buttons or colored messages for better interaction and clearer info texts.
On a side note, is it currently possible to get the sender of a message?

**Comment by dustinchilson** [comment]
I've got this working in my fork. I've moving things around so unless you want all my changes It'll need to be extracted. If you're interested I could make a pull request.

**Comment by mattcbaker** [comment]
@senj I am still trying to understand the use case for sending atrachments. Do you have a specific example? Including the sender is a great idea! I created an issue for it: https://github.com/mattcbaker/dotnetcore-slackbot/issues/4

**Comment by mattcbaker** [comment]
@dustinchilton a PR would be great! I'm curious - what are you using the attachment functionality for?

**Comment by dustinchilson** [comment]
We use it to send more detailed information to the user. Attachments allow for colors and more structure

![image](https://cloud.githubusercontent.com/assets/69644/23959918/df24f538-097c-11e7-914c-0f33d05b5b45.png)

![image](https://cloud.githubusercontent.com/assets/69644/23959937/ec23ad2e-097c-11e7-85cf-d861fae46e39.png)

**Comment by mattcbaker** [comment]
@dustinchilson ah - that makes total sense. I will check out the PR you just pushed.
@senj I closed https://github.com/mattcbaker/dotnetcore-slackbot/issues/4, resolved it with 9365d2d3ef47942fa1972f9df8c364cd9921114b

**Comment by mattcbaker** [comment]
Conversation about this going on over here: https://github.com/mattcbaker/dotnetcore-slackbot/pull/5

**Comment by dustinchilson** [comment]
Submitted a new pull request #10
